---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
spec:
  encryptedData:
    config.production.json: AgBsjYh7iHCLSwTBJ4QfvI2wFacwV/Yi9LKaqsrLUBZHtpadbi9Wx7Rv+1WtAQTivVu4E+ORbwXxouMwjQzTAlO7QV21zNQAWA7HByOczrtRE5hhs8LDRffxlVG1xdy08enzV8U8Mq8ouEA0BoOgwIe0o9jiwHzil2yZjPyWf6Ukst9PIGt8DXTt9kcSxHAln5CSe7PrzEeEy1YtDaRwyaOa4+Rd67eVTh2ffBNyl5fBKQQiyG+R9balK8OgUG8e2OwTitqsq9UMOLXBD/ARKV4YBsXvteYuDQOOTYqyvXmLT0Sm6tgkBVDRY6ZlI3nDsgb7SSAFiJSJd/YncxaoD4bQ/mYUN+KzO0X8INCrlXv9T1iuNai12gwx+MuQs/m75F5/7cCYE/AMjv8GHqJ8zZExEHBzHetDwE/dHLv72HwEUFKtNjvxu4AftV8WXs1/kFc6m4ZSp9pRFiZkfLa8gIdB/uEdadJFE7U+pYqc5NKeo0zToS0f8Eiz1LAQkhzXTQ1Q9BjNy1mVnU/31izLG34DNznGsxSd433CJJfONQQpDFs/uo5pIGeCHTWKPL4ou+KmcdpD/Uo3VfmEjXfAGq16jk/gTTkWOGADEmSxZ+IBleybzHabvbkzB3f2ZiGXh7LjUMZAQd8jU6mhNnq2BP14KNd6y7/7wYeZvs/TQenKiyQS6x0eoRenWnt7SrBO8XtHztS7H3gYd1bk8zupN3KZM6+f9MRppYe8MCc7XzzYp7EOqEJ3qgAzAcJ1DDNPfTaE+7dSuF4LhK95AAl0zWd/PrX7a56wtURMpC8QQq+Gw8eCc265U9IgE+1oHPUh+I5NYk5HND/q1fwk9u6ZyCI2h5gG4cdszugTAiU+E63AHje6zPY83y7vECMdcKXjbkkavwVVMwMHSd/r9jT7XFon969W9ZFGgh0F7tWQO89E5Jf2+T++n84XGKnqTI6ropzob1kFADolQBCpiKUeySUGmiuxppXaLEHVBpEIH1xOAAGO6QlGUDwhR2ZwTfMG+cmMl7kKnJHnWMIK99VUsWLYd/TEvkNN1D/y6oeNVBpNgcKy40UiJM98mvm7fxr9Rb9CN5xpu+Nenvg0hJeMeL2gCY/1iDzstheF49FXLk6NF9ixqLZF20SJiGYaC2cAs4TzOIdZ6ezugfZrBwWyjsg5S73O3lhkC4oqJ0RtLLHBL/2FvlG4k9FsdRlSluKsYfcD0mfKQR27aXJ51cLiKVeyuv8gZUjS2ZhsVuFw7HGB9XVtSVLeOSzcsWA4vp4IzQcN8GdAykZwsoFhbkzNUjPjq78HtrTOjMW2jKW6NGN+qAqyXhxJlrd02xAQ/gk+q/1SgUGnVn8wsD3gUo38KuHbcBWFIwKQIjuGCsIMub0Ckm4cfW6Dssr01eDLOWoC8vRSvpaVD0Al0WpPhRYnwSq78bp796esZ6I4scB+4RBvyK4vhVCPeA0NxJd5ogftezd3R87yHMU8R3tgFJedKL4NXrNf5btfqgwY+SQ0Tvc3VUQ/3kVdWI3caFFJecfCkr7KB1qtuIso9p4LftVfn6NdKpnq6/Eh5VQkM9/0Fut8vwme/8mi4+lKDx9PSEw55SnleIA3SE8i20wf8O8yBVFC7UrhxrMwulctEvAWuRobXne18lD78CLT9rYgfsXwNpBK8z96MOzPrFl80ZJocCO+BucCCFSgQmCpLi7KHD86v6+eg3TlUdbtahCwkBkGyyktGtEbKKvOlbZIs5ue/JIFOp0Kc72cK+PxZ86ONhGWE+sFBcljTji2SQOXgJn+dCoNE2ulONWn04/m9zuIrx935D8+P5pgf4ZPmJSaoHP4XT0vYadzCnXzdKU7GqJ/RUg=
  template:
    metadata:
      labels:
        app: ghost-on-kubernetes
        app.kubernetes.io/component: ghost-config
        app.kubernetes.io/instance: ghost-on-kubernetes
        app.kubernetes.io/name: ghost-config-prod
        app.kubernetes.io/part-of: ghost-on-kubernetes
        app.kubernetes.io/version: "5.92"
      name: ghost-config-prod
      namespace: ghost-on-kubernetes
    type: Opaque
