---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
spec:
  encryptedData:
    config.production.json: AgB956x7iT0H48nWjRWQXwDqKO4TwdRIxY5NGxJkaQtPz50jQLCSarMnLux+qu54ipw3/AxEr0LWSpKrFqqPLY/RnyUsKaDZe92Gm7LkbxtpAIP1mSYnrKrehSyG0LKwtileUkRkjj/ArhvB6VffDzs+f/UI+cG4AD+G1k9vK4j1yr/w+s4FbMaUH68ac/bM7ifh3yU/H9NAdB9mSA83wsHPZMnwLfyD26v+vLj7ud+osiCUS2O8eplG3uCn30HEOaYjh2W2MI1XAah44Po6QP70cqopPjV1oRp1voFx1fAMS8tbvyu+qvNyR3xWM3SIri4mBdAqYOgdr3x8u1jPqoDWYGxPWlkmD4sewvrP7sSJ/7SlQqCujVsLBELjxZzSIE8pfZ4bezFU1R9CTRuUW0nhB6lLamB7h2zsg75h/BvGlBo0pXap90MJOt7WK0jKqkQSMurs9nT8Uib3RQkVKoB/CFtKftvOVuuubD6UHGHNeI8OpA+mWiV1HLooICCnSXLPDsRPZ/UDBVRF+fKZSCuv3Ti2fyyy9YiSTeVzmoxWV4F4MMUNLQ49zBasFL2lOGkAcNNaL+LKYqRRaWkiQ0om1CXuTPMXk4/J3R9I63k0776A8kbaid6dKnvrCCic+L39VO1g2h1K5CTZ56yeSEfqQzW4buO4S2hvsg3rIROi0HZjcesiQjj7ZQ9CpLvkkC7P/ep5VW0oIjTjQu4l3c3b5d5/a0Wychw/ld8q7JM0bEdPNdraehLNEC/QDuz0GBQshrpYR9syPhZntxokY4RWosSigKt87bsaiXXsYFULQwedlv5OXGoDQ5Wo+pajKz09Wkb83xYNsnUSfDk4I6ZTgC38SM47yAH022NvV45hXsb5LQK19JoNeToESqr5/TvE9EHasGB0mfU46Xtm7USbR/4mjp7ytyiJFxHSYGeB+RGQT0w3mYCKkg7DeE9VWoDkwPgN3ioY7ZujNVkeYb8/K6aw117ZiMG02mMaY0ThL0QtNJi4EnFO8Cu0BFAvr3UBjUJ/ZH/TlDmeO4j0pVWr5r18gMkAxanY9WWsQE1vSCnI8ULOfWX0sWoT19BXZmtXtM+Dw3NTksWGtz9+3x9StH2fO5ADZ7PJ5TcDSdQFsWKUYroMcOeMMsHCdyqet0mJam5sC+bXFFuNo7W4V4iwsjSyYK5+lbKgVq7IZ9LIPJ+aUnnYw0L3Jo1Xqj83o3mqCAau+K0nQEkBzVH15W6rymLwkZfPRgsrTz7cGk+N9yMShTlQrRsAe1OaBKTFJOL1h5lfLKjMANFv39b79gy4WtuE+KoAUonpWHHKXJeJ84/ng7NAE16U/QsDToI8y+z5agOjkoDHWStZhgl3HvwNz6uw3GEooFLcciIiAkDI/ET/RQe1cTd37B0Upoe3AO3ZSBybb9lql9CiSZbwAG221U+vr/JUqiGEuF20Th79qcY4AgZD714ORcQqkCm04Enl3URzM1lbxYz60sqJ3sr0MXbXmycOHdLwV31ZLsqgU4myI9P1oHm56odEtwokqqTcmnrzQ3eb8cGpzCQcOuQgLUxFJ0o1jQPDKEF8FZAhPMEhblKnrKrWNsblBYy8ZrUfk+NcdvzgT9sfe9zFm9LlM7gP+FUHQJK3/H0LfHbSDnTjXQfKR5R5fSiYVrCGVmm3EX5ylulf6lir3ajMyfSW6/6HPxYiWD4UBb8joSSnzzYLCvQ0NBclNrEK1FVk7cSD4xuuzH1d0nnVveMP9MhMSqFGPIcKHiCF5/0dB/oTZXu4GuxNNKAn7LLB+hFTwec/UPC5PlRuhk/ajoFws8P8zKTDWtFo+ftvD84rSM8aaYiGfLxdMG8WQJg=
  template:
    metadata:
      labels:
        app: ghost-on-kubernetes
        app.kubernetes.io/component: ghost-config
        app.kubernetes.io/instance: ghost-on-kubernetes
        app.kubernetes.io/name: ghost-config-prod
        app.kubernetes.io/part-of: ghost-on-kubernetes
        app.kubernetes.io/version: "5.92"
      name: ghost-config-prod
      namespace: ghost-on-kubernetes
    type: Opaque
