---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
spec:
  encryptedData:
    config.production.json: AgCcWv3MGw0+5oyoVGoyVpNmNgrEjhCM8BJQPgHVV2iv7/orecykpXL7SFTlPJjRMTdRLK8q9gMNpQsUrcffCFS7O+Aq++264cghAlNpvf83kg7JAs8sMTShgZzhiXCx159zJgBbAos3B4E8saoESm1S2svLWLE0zB+X2PJVUCvnFdYx1sxf4xMY8wLWlpWc1Bp5eOosjGw/+NeebsdfMFGOwfGVBqa+uHxVsyC1v9nh8WpUgRiNbnMs86juiDDNcSY/15JG2JyJQqKW/oNeUmbOGQ5IgZcZUVDnovSvfbCiVVObSWGYGRfBTXNwGw4n1AsZDZPypqfO72rdA++i4D6ABWVzQ1sZUcQSIFdycjZ3rjcRBxXygAzQiIDRGksWKKPWQPssuxWudkhgBE4qiInxRirmlxakw4pHOwx8J/goW6kiojdvBhH4eZS4IR2VMWMDfnfaYn7jZ9Y+sYKbVwGB9qcNRQ+vtKseE8GXNHkA8/X+YezBKrPOrRX4uW+GOn5JyWj9Iw90JJju1+Wg+WLRTXbvscCLeuJkVSC9h8631eKX54r1ulBeNoVUZD+17cPsaV41wKuJNN5aQFXTUdqU50dPhwVEsaojxz7YQ6+j1DUX7eOl5E5phfj815XPh/SbAKNukt4SjDHuCQWBCntlW8+zfdV2YdemZRYh3Mdi7oN/yzT0jvKYHY66zLXyUWnI8GLDGKyJtZwe60Gj4gSfoP/i3DeOQ8FpaZgBKxgtIOYoEfTWefc5GRZK2Pu0HrikHUica7e/mnK7hRYe0CScjwxPNd0vJxdKqMGcQbwG568GgsDMfjisQNwosXnRxQVy5hXh0zK9YZJ+q3NsL6CQUkYH2gVVBjDtRp+6cawH0mdiGB0aW1MOKAqXWk7Ajw32ZIhXjWtPjq1x3b9j/NVdw17IIF4OStj/rfUgFyFgM8SoM50SPgIroj9TQSRUCUEwjBvB6ROY+kisVpJy+FW1uU/3ygSKL7DUUP5NaZMgga/oQu1+Nlg6qfy8mJw29cjj8vdlFB9/NGbvwig+BVscDNIAdBPVZY7aombPnT0W6QDwHUsJ1OpfRv6V/422ghbim5slSvH2WQBjZXZ+DKCrcolBsEK4nt2VW/FMoJKMUbp15jLUhbFkt5cgoyefjhkSOoLk4+YbPb0lYsnufw1D6zsCyzk8LuUvIfeJs9h5rUf5XT4wwg53xVZgVyhsUM7w7hnaHXo4DgHpRD1CxvNpQ5ojqH44Jgy2boauP9L6dtfK7kOM5VBM8eY6eKrfsolQo+dVMfDPz2JMntt9My8ON5uFwp1FkzVBR82kvYfs/fjww+2NRwSWb2uEUpn9I1ggyltIQn7MR9MwiRy9RVclAQN+887V26bm2PTd+fl4t9kvJhLgT+Es8dU+bc6J6thjYtrLat9VWimNeTGXsTVya7WQXbvAKcwpsqsIgeCGxpj8ui8yfXWXeOsERi/+aix4ouMWxqnGID4MXo40pHoUSkPhDNZjAQsyYGJcEeV0qSVkaPbfOCJh3/CCBMNfAwPMt/OnU+MIA79oOiwWd6KvWXQ+lLJ9K/fzlVnaRozTHj1vJd6KgLHOfMxoEg4kkJpggeIK2pa34ZU8qbHpbZgodiI1Z3iZXVA4Xp4SSKAXSno/r4FFkLUeJnRISdRwZMVqglQvSHUeu9Qa3wEDVhUCdee2AyMhGbqdI/OL4l+JMzNetq5L/ksvjSKP4fY11GfiSvjrWUT8phwY18B/cVgFTN3Itk4I3BwxHRE98z76w9a5HGIo4W+kz48dPdNLGj9su/ryhe6T5GSKiGGWm9JpiHEalsTVDyxnF5DfxsQt4dtqru65AHjcZRHEZUBQngIui6/jJn30OR6TLyibwaY=
  template:
    metadata:
      labels:
        app: ghost-on-kubernetes
        app.kubernetes.io/component: ghost-config
        app.kubernetes.io/instance: ghost-on-kubernetes
        app.kubernetes.io/name: ghost-config-prod
        app.kubernetes.io/part-of: ghost-on-kubernetes
        app.kubernetes.io/version: "5.92"
      name: ghost-config-prod
      namespace: ghost-on-kubernetes
    type: Opaque
