---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared-tunnel
spec:
  encryptedData:
    token: AgBzz8pMkSNZqiYL4ypx1/8gEuKqGk6G7iBXKG1d8A/bNkd+KgKtW/XoDzQdMRjki36ZXv4UEVLg5dAVMdJC153/ZUrRxcrVA1q+oLESsUODo2XOp/ZnZj77YKvQraxbJIFSOU2Lqs8DJuR2ZSYDiKhkQqXOPAHHVELiO9G7RFkLOfdnhqPDEOsilyyvjzzQrUsPkFVnopudh46DW0mlpKr299nbS1/vPf2D+CWoMm4EVSer6lT29ofEqTSoQgPKDNdWHfJ1yOx0CTtamlkBLUj8SDSrlI4ehiaRi7L90WIzSKxKpeZvrLRDsHxdVg91Qp1RlNUlQyiG6g08HCZlkxhKsDPbiOdBKAy9yhZKqyihhOrDLsFqOrh7Ou9toN4ZltbvE2e7Bt8f4d/ZOQu2vIHgqWgiF/3dPH6/Pos6G0bhQv9ZydnpX7SKd5j5zZ+luf+YwHdNZtiTuTEul2R0farFGgaY4bBCb/+0T+h4eP1mKU/CWhSkyf7CeApKJn+nlrNU/AQ8h/SdgCoDtzjGqtsv16pDUYqdwzOyZ0i49Fyz6e7iNo1KaBU5IY2L7u14r9RDLPJcGn3jFRN+adOCQPlnI8/yQgEiVYZQ9bOxx6WxrWzE0OnFRkqYHvsX8wtKT75nxZ5B0Gj2FOxVZZfcmWAyeKBlEuwIEU8qMggTBVU7ZGpQtU4z3+3idmqE8PPChwv80k8QWyO/GHLJke0oFCaSqjQ40PlBeFq77Bjb9LaEcabjzqctXk+epb9HXnJG5OhlHQd4scY5RZzp+JQRUtmF2/kcXmLUV+ZpydorZ35nLgOT+SBruc5OQZxkWtiaVTs/dOx37NhPA8UF10NS6C/m0X2g8D8jytQBQGurzYhFkC5PNCFOjA7g9X/c+XoIb94NohsiWIvAkPgw4AR2fb4c8cIUdM5dLq8Ugt/ZZCdJgjG6ZQxt4QWj
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared-tunnel
